apiVersion: v2
name: guestbook
appVersion: "1.0"
description: A helm chart to test
version: 0.1.0
type: application
dependencies:
  - name: wordpress
    version: 9.0.x
    repository: https://charts.helm.sh/stable